### ISSUE TITLE
Spezifikation online lesen und Downloads funktionieren nicht mehr – Links fixen?

### ISSUE THREAD

**Issue by gruenzeug** [OParl/spec-website#2]
Auf https://oparl.org/spezifikation/ zeigt der Link „[Entwurf der Spezifikation kann] online gelesen werden“ nur wieder auf https://oparl.org/spezifikation/ statt auf eine online lesbare Version.
Die Downloadlinks für alle Dateiformate zeigen auf nicht mehr vorhandene Dateien – vermutlich wurde das Schema des Dateinamens geändert?

Kann leider selbst keinen Fix anbieten, ich blicke da nicht durch. Hoffe dieser Hinweis hilft. Wenn nicht einfach schließen :)

**Comment by the-infinity** [comment]
Mittlerweile fixed. :)
